spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dp_be_db
    username: postgres
    password: Wngurdl1!
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: create
  logging:
    level:
      org.springframework: DEBUG
      org.hibernate.SQL: DEBUG
